name: product_detail
description: Turkcell Siparisim ürün detay ekranı
publish_to: 'none'
version: 1.1.3
homepage:

environment:
  flutter: ">=3.10.6"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  get: any
  flutter_svg: any
  connectivity: any
  intl: any

  sip_models:
    git:
      url: https://github.com/dophub/sip-models.git
      ref: prod


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  assets:
    - assets/images/