name: product_detail
description: Turkcell Siparisim ürün detay ekranı
publish_to: 'none'
version: 1.0.2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  get: any
  flutter_svg: any
  connectivity: any
  intl: any

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/